config/routes.rb
Rails.application.routes.draw do

  get 'orders/reservation/:idResto', to: "orders#index", as:"reservation"
    get '/addperson', to: "orders#addperson", as:"addperson"

  # Page d'accueil
  root to:'restos#index'

  # restaurant
  resources :restos

  devise_for :clients, controllers: {
  	confirmations: 'confirmations' 
  }
  
  devise_scope :client do  
   get '/clients/sign_out' => 'devise/sessions#destroy'     
end
  
  # menus
  get '/menus/:idResto', to: "menus#restomenus", as:"restaurants_menus"
  get '/menus/:id', to: "menus#show", as:"menu"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :orders #un client 1 ---- N  commande
end

app/models/menu.rb
class Menu < ApplicationRecord

	   #relation resto N-N menu
    has_many :menu_restos
    has_many :restos, through: :menu_restos

end

app/models/menu_resto.rb
class MenuResto < ApplicationRecord

	    #relation Menu N-N Resto
    belongs_to :menu
    belongs_to :resto
    

end

app/models/order.rb
class Order < ApplicationRecord
	    belongs_to :client      #un client 1 ---- N  commande
	    belongs_to :resto      #un Resto 1 ---- N  commande

end

app/models/resto.rb
class Resto < ApplicationRecord

	   #relation resto N-N menu
    has_many :menu_restos
    has_many :menus, through: :menu_restos
    has_many :orders #un client 1 ---- N  commande

end

app/models/static_page.rb
class StaticPage < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
private

    def after_confirmation_path_for(resource_name, resource)
      sign_in(resource)
      root_path
    end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
	def index

	end
	
	def show
	end

	def restomenus
		@resto = Resto.find(params[:idResto])
		@menus = @resto.menus
		@resistances = @menus.where(category:"Résistance")
		@entrees = @menus.where(category:"Entrée")
		@desserts = @menus.where(category:"Dessert")
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	def index
		@resto = Resto.find(params[:idResto])
		@menus = @resto.menus
		@datamenus = []
		@menus.each do |menu|
			@datamenus.push([menu.category,menu.name,menu.description,menu.price,menu.duration,menu.id]) 
		end
		puts @resto.id
	end

	def addperson


	end
end

app/controllers/restos_controller.rb
class RestosController < ApplicationController
  def index
    @restaurants = Resto.all
  end

  def show
    @restaurant = Resto.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    restaurants = Resto.all
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/orders_helper.rb
module OrdersHelper

end

app/helpers/restos_helper.rb
module RestosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodStore</title>
      <link href="favicon.png" rel="icon">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
        
      <link href="https://fonts.googleapis.com/css?family=Poppins:300,300i,400,400i,600,600i,700,700i|Satisfy|Comic+Neue:300,300i,400,400i,700,700i" rel="stylesheet">
      <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>
  </head>

  <body>
  <%= javascript_pack_tag 'main.js' %>
    <%= render 'parse/navigation' %> 
    <%= yield %>
    </footer>
      <%= render 'parse/footer' %>
    </footer>
    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

app/views/menus/restomenus.html.erb
    <!-- ======= Menu Section ======= -->
    <section id="menu" class="menu">
      <div class="container">
        <div class="section-title">
          <h2>Notre <span>Menu</span></h2>
        </div>
        
        <h2>Entree</h2>
          <div class="row menu-container">
          <% unless @entrees.empty? %>
            <% @entrees.each do |entree|%>
              <div class="col-lg-6 menu-item filter-starters">
                <div class="menu-content">
                    <a href="#"><%= entree.name %></a>
                    <span><%= entree.price %> Ar</span>
                </div>
                <div class="menu-ingredients">
                  <%= entree.description %>
                  <br><strong>Duration: <%= entree.duration %> min</li></strong>
                </div>
              </div>
            <%end%>
          <%end%>

          <div class="col-lg-6 menu-item filter-specialty">
            <div class="menu-content">
              <a href="#">Bread barrel</a><span>$6.95</span>
            </div>
            <div class="menu-ingredients">
              Lorem, deren, trataro, filede, nerada
            </div>
          </div>
           <div class="col-lg-6 menu-item filter-specialty">
            <div class="menu-content">
              <a href="#">Bread barrel</a><span>$6.95</span>
            </div>
            <div class="menu-ingredients">
              Lorem, deren, trataro, filede, nerada
            </div>
          </div>
           <div class="col-lg-6 menu-item filter-specialty">
            <div class="menu-content">
              <a href="#">Bread barrel</a><span>$6.95</span>
            </div>
            <div class="menu-ingredients">
              Lorem, deren, trataro, filede, nerada
            </div>
          </div>
           <div class="col-lg-6 menu-item filter-specialty">
            <div class="menu-content">
              <a href="#">Bread barrel</a><span>$6.95</span>
            </div>
            <div class="menu-ingredients">
              Lorem, deren, trataro, filede, nerada
            </div>
          </div>
           <div class="col-lg-6 menu-item filter-specialty">
            <div class="menu-content">
              <a href="#">Bread barrel</a><span>$6.95</span>
            </div>
            <div class="menu-ingredients">
              Lorem, deren, trataro, filede, nerada
            </div>
          </div>
      </div>
     <hr>
      <h2>Resistances</h2>
         <div class="row menu-container">
          <% unless @resistances.empty? %>
            <% @resistances.each do |plat|%>
              <div class="col-lg-6 menu-item filter-starters">
                <div class="menu-content">
                    <a href="#"><%= plat.name %></a>
                    <span><%= plat.price %> Ar</span>
                </div>
                <div class="menu-ingredients">
                  <%= plat.description %>
                  <br><strong>Duration: <%= plat.duration %> min</li></strong>
                </div>
              </div>
            <%end%>
          <%end%>
           <div class="col-lg-6 menu-item filter-specialty">
            <div class="menu-content">
              <a href="#">Bread barrel</a><span>$6.95</span>
            </div>
            <div class="menu-ingredients">
              Lorem, deren, trataro, filede, nerada
            </div>
          </div>
           <div class="col-lg-6 menu-item filter-specialty">
            <div class="menu-content">
              <a href="#">Bread barrel</a><span>$6.95</span>
            </div>
            <div class="menu-ingredients">
              Lorem, deren, trataro, filede, nerada
            </div>
          </div>
           <div class="col-lg-6 menu-item filter-specialty">
            <div class="menu-content">
              <a href="#">Bread barrel</a><span>$6.95</span>
            </div>
            <div class="menu-ingredients">
              Lorem, deren, trataro, filede, nerada
            </div>
          </div>
           <div class="col-lg-6 menu-item filter-specialty">
            <div class="menu-content">
              <a href="#">Bread barrel</a><span>$6.95</span>
            </div>
            <div class="menu-ingredients">
              Lorem, deren, trataro, filede, nerada
            </div>
          </div>
        </div>
     <hr>
        <h2>Deserts</h2>
         <div class="row menu-container">
          <% unless @desserts.empty? %>
            <% @desserts.each do |dessert|%>
              <div class="col-lg-6 menu-item filter-starters">
                <div class="menu-content">
                    <a href="#"><%= dessert.name %></a>
                    <span><%= dessert.price %> Ar</span>
                </div>
                <div class="menu-ingredients">
                  <%= dessert.description %>
                  <br><strong>Duration: <%= dessert.duration %> min</li></strong>
                </div>
              </div>
            <%end%>
          <%end%>
           <div class="col-lg-6 menu-item filter-specialty">
            <div class="menu-content">
              <a href="#">Bread barrel</a><span>$6.95</span>
            </div>
            <div class="menu-ingredients">
              Lorem, deren, trataro, filede, nerada
            </div>
          </div>
           <div class="col-lg-6 menu-item filter-specialty">
            <div class="menu-content">
              <a href="#">Bread barrel</a><span>$6.95</span>
            </div>
            <div class="menu-ingredients">
              Lorem, deren, trataro, filede, nerada
            </div>
          </div>
           <div class="col-lg-6 menu-item filter-specialty">
            <div class="menu-content">
              <a href="#">Bread barrel</a><span>$6.95</span>
            </div>
            <div class="menu-ingredients">
              Lorem, deren, trataro, filede, nerada
            </div>
          </div>
           <div class="col-lg-6 menu-item filter-specialty">
            <div class="menu-content">
              <a href="#">Bread barrel</a><span>$6.95</span>
            </div>
            <div class="menu-ingredients">
              Lorem, deren, trataro, filede, nerada
            </div>
          </div>
        </div>
    </section><!-- End Menu Section -->

app/views/orders/index.html.erb
<div class="container" style="margin-top: 6%;">
	<center><h2>RESERVER dans "<%= @resto.name %>"</h2></center>
	<div class="row">

		<!-- =====RESERVATION===== -->

		<div class="col-sm-9" >
			<h3>COMMANDES</h3>

			<!-- session js -->
			<%= form_tag(addperson_path,id:"form-data",'data-menus':"#{@datamenus}", 'data-resto':"#{@resto.id}") do %>

			<i> Nombre des personnes : </i>
			<a href="javascript:void(0)" class="btn btn-info" id = 'deleteperson'>-</a>
			<strong><span id = 'nbr_person' data-person=0> 0 </span> </strong>
			<a href="javascript:void(0)" class="btn btn-info" id = 'addperson'>+</a>
			<hr>

			<div id="menuPersonne">


			</div>

			<%end%>
		</div>

		<!-- =====PANIER PANIER ====-->

		<div class="col-sm-3" >
			<center><h3>PANIER</h3></center>
			<div id="res-order">


			</div>
<div class="alert alert-info">Prix total : <span id='total_price'>0 Ar</span></div> 
			<div>

				<%= submit_tag("valider") %>
			</div>
		</div>

	</div>


</div>


<script src="/js/order.js"></script>

app/views/parse/_GoogleMap.html.erb
<div class="map">
    <iframe style="border:0; width: 100%; height: 350px;" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12097.433213460943!2d-74.0062269!3d40.7101282!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb89d1fe6bc499443!2sDowntown+Conference+Center!5e0!3m2!1smk!2sbg!4v1539943755621" frameborder="0" allowfullscreen></iframe>
</div>

app/views/parse/_allrestaurants.html.erb
<!-- ======= restaurants lists ======= -->
<body id="menu">
<section id="why-us" class="why-us">
  <div class="container">

    <div class="section-title">
      <h2>Les Restaurants <span>le plus proche de votre position</span></h2>
      <p>Ut possimus qui ut temporibus culpa velit eveniet modi omnis est adipisci expedita at voluptas atque vitae autem.</p>
    </div>

    <div class="row">
      <% @restaurants.each do |resto|%>

      <div class="col-lg-4 mt-4 mt-lg-0">
        <a href="<%= resto_path(resto.id) %>">
          <div class="box">
            <div class="hei">
              <span><%= resto.name %></span>
              <h4><%= resto.adress %></h4>
            </div>
              <p class=""><%= resto.description %></p>
          </div>
        </a>
      </div>
      
      <%end%>
    </div>
  </div>
</section>
</body>

app/views/parse/_footer.html.erb
  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <h3>FoodStore</h3>
      <p>Et aut eum quis fuga eos sunt ipsa nihil. Labore corporis magni eligendi fuga maxime saepe commodi placeat.</p>
      <div class="social-links">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
      <div class="copyright">
        &copy; Copyright <strong><span>FoodStore</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <a href="tsiryjl.github.io/NewPortfolio">TsiryJL</a>
      </div>
    </div>
  </footer>
  <!-- End Footer -->

app/views/parse/_index.html.erb
    <!-- ======= Gallery Section ======= -->
    <section id="gallery" class="gallery">
      <div class="container-fluid">

        <div class="section-title">
          <h2>Les Restaurants <span>le plus visiter</span></h2>
          <p>Ut possimus qui ut temporibus culpa velit eveniet modi omnis est adipisci expedita at voluptas atque vitae autem.</p>
        </div>

        <div class="row no-gutters">

          <div class="col-lg-3 col-md-4">
            <div class="gallery-item">
              <a href="assets/img/gallery/gallery-1.jpg" class="venobox" data-gall="gallery-item">
                <%= image_tag  "gallery/gallery-1.jpg", :class => "img-fluid" %>
              </a>
            </div>
          </div>

          <div class="col-lg-3 col-md-4">
            <div class="gallery-item">
              <a href="assets/img/gallery/gallery-2.jpg" class="venobox" data-gall="gallery-item">
               <%= image_tag  "gallery/gallery-2.jpg", :class => "img-fluid" %>
              </a>
            </div>
          </div>

          <div class="col-lg-3 col-md-4">
            <div class="gallery-item">
              <a href="assets/img/gallery/gallery-3.jpg" class="venobox" data-gall="gallery-item">
                <%= image_tag  "gallery/gallery-3.jpg", :class => "img-fluid" %>
              </a>
            </div>
          </div>

          <div class="col-lg-3 col-md-4">
            <div class="gallery-item">
              <a href="assets/img/gallery/gallery-4.jpg" class="venobox" data-gall="gallery-item">
                <%= image_tag  "gallery/gallery-4.jpg", :class => "img-fluid" %>
              </a>
            </div>
          </div>

          <div class="col-lg-3 col-md-4">
            <div class="gallery-item">
              <a href="assets/img/gallery/gallery-5.jpg" class="venobox" data-gall="gallery-item">
                <%= image_tag  "gallery/gallery-5.jpg", :class => "img-fluid" %>
              </a>
            </div>
          </div>

          <div class="col-lg-3 col-md-4">
            <div class="gallery-item">
              <a href="assets/img/gallery/gallery-6.jpg" class="venobox" data-gall="gallery-item">
                <%= image_tag  "gallery/gallery-6.jpg", :class => "img-fluid" %>
              </a>
            </div>
          </div>

          <div class="col-lg-3 col-md-4">
            <div class="gallery-item">
              <a href="assets/img/gallery/gallery-7.jpg" class="venobox" data-gall="gallery-item">
                <%= image_tag  "gallery/gallery-7.jpg", :class => "img-fluid" %>
              </a>
            </div>
          </div>

          <div class="col-lg-3 col-md-4">
            <div class="gallery-item">
              <a href="assets/img/gallery/gallery-8.jpg" class="venobox" data-gall="gallery-item">
                <%= image_tag  "gallery/gallery-8.jpg", :class => "img-fluid" %>
              </a>
            </div>
          </div>

        </div>

      </div>
    </section>
    <!-- End Gallery Section -->

app/views/parse/_navigation.html.erb
 <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center">

      <div class="logo mr-auto">
        <h1 class="text-light"><a href="<%= restos_path %>"><span>FoodStore</span></a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>

      <nav class="nav-menu d-none d-lg-block">
        <ul>
          <li class="active"><a href="<%= restos_path %>">Home</a></li>

          <li><a href="#about">About</a></li>
          <li><a href="#menu">Menu</a></li>
          <li><a href="#specials">Specials</a></li>
          <li><a href="#events">Events</a></li>
          <li><a href="<%= new_resto_path %>">équipe</a></li>
          <li class="book-a-table text-center"><a href="#" style="width:13em; height:3.3em;">Connexion</a>
            
            <%if client_signed_in?%>   
              <ul class="drop-menu menu-4">           
                <li><%= link_to "Se deconnecter", destroy_client_session_path, method:"delete"%></li> 
              </ul>
            <% else %>
              <ul class="drop-menu menu-4">
                <li><%= link_to "Se connecter", new_client_session_path %></li> 
                <li><%= link_to "S'inscrire", new_client_registration_path %></li> 
              </ul>
            <% end %> 
          
          </li>
        </ul>
      </nav><!-- .nav-menu -->
    </div>
  </header><!-- End Header -->

app/views/restos/create.html.erb
<h1>Restos#create</h1>
<p>Find me in app/views/restos/create.html.erb</p>

app/views/restos/destroy.html.erb
<h1>Restos#destroy</h1>
<p>Find me in app/views/restos/destroy.html.erb</p>

app/views/restos/edit.html.erb
<h1>Restos#edit</h1>
<p>Find me in app/views/restos/edit.html.erb</p>

app/views/restos/new.html.erb
    <!-- ======= Chefs Section ======= -->
    <section id="chefs" class="chefs">
      <div class="container">

        <div class="section-title">
          <h2>Notre superbe<span>Teams</span></h2>
          <p>Ut possimus qui ut temporibus culpa velit eveniet modi omnis est adipisci expedita at voluptas atque vitae autem.</p>
        </div>

        <div class="row">

          <div class="col-lg-4 col-md-6">
            <div class="member">
              <div class="pic">
              <%= image_tag  "chefs/chefs-1.jpg", :class => "img-fluid" %>
              </div>
              <div class="member-info">
                <h4>Tsiry RAZANAKOTO</h4>
                <span>Front-end Developper</span>
                <div class="social">
                  <a href=""><i class="icofont-twitter"></i></a>
                  <a href=""><i class="icofont-facebook"></i></a>
                  <a href=""><i class="icofont-instagram"></i></a>
                  <a href=""><i class="icofont-linkedin"></i></a>
                </div>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6">
            <div class="member">
              <div class="pic">
                  <%= image_tag  "chefs/chefs-2.jpg", :class => "img-fluid" %>
              </div>
              <div class="member-info">
                <h4>Sarah Jhonson</h4>
                <span>Patissier</span>
                <div class="social">
                  <a href=""><i class="icofont-twitter"></i></a>
                  <a href=""><i class="icofont-facebook"></i></a>
                  <a href=""><i class="icofont-instagram"></i></a>
                  <a href=""><i class="icofont-linkedin"></i></a>
                </div>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6">
            <div class="member">
              <div class="pic">
                  <%= image_tag  "chefs/chefs-3.jpg", :class => "img-fluid" %>
              </div>
              <div class="member-info">
                <h4>William Anderson</h4>
                <span>Cook</span>
                <div class="social">
                  <a href=""><i class="icofont-twitter"></i></a>
                  <a href=""><i class="icofont-facebook"></i></a>
                  <a href=""><i class="icofont-instagram"></i></a>
                  <a href=""><i class="icofont-linkedin"></i></a>
                </div>
              </div>
            </div>
          </div>

        </div>

      </div>
    </section><!-- End Chefs Section -->

app/views/restos/show.html.erb
<!-- ======= Resto Section ======= -->
<section id="hero">
  <div class="hero-container">
    <div id="heroCarousel" class="carousel slide carousel-fade" data-ride="carousel">
      <ol class="carousel-indicators" id="hero-carousel-indicators"></ol>

      <!-- Slide 1 -->
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>

        <div class="carousel-inner">
          <div class="carousel-item active">
            <%= image_tag  "slide/slide-1.jpg", :class => "d-block" %>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2 class="animated fadeInDown"><span><%= @restaurant.name %></span> Restaurant</h2>
                <p class="animated fadeInUp"><%= @restaurant.description %></p>
                <div>
                  <a href="<%= restaurants_menus_path(@restaurant.id) %>" class="btn-menu animated fadeIn scrollto">Nos menus</a>
                  <a href="<%= reservation_path(@restaurant.id) %>" class="btn-book animated fadeIn scrollto">Réserver</a>
                </div>
              </div>
            </div>
          </div>

          <!-- Slide 2 -->
          <div class="carousel-item">
            <%= image_tag  "slide/slide-2.jpg", :class => "d-block w-100" %>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2 class="animated fadeInDown"><span><%= @restaurant.name %></span> Restaurant</h2>
                <p class="animated fadeInUp"><%= @restaurant.adress %></p>
                <div>
                  <a href="<%= restaurants_menus_path(@restaurant.id) %>" class="btn-menu animated fadeIn scrollto">Nos menus</a>
                  <a href="<%= reservation_path(@restaurant.id) %>" class="btn-book animated fadeIn scrollto">Réserver</a>
                </div>
              </div>
            </div>
          </div>

          <!-- Slide 3 -->
          <div class="carousel-item">
            <%= image_tag  "slide/slide-3.jpg", :class => "d-block w-100" %>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2 class="animated fadeInDown"><span><%= @restaurant.name %></span> Restaurant</h2>
                <p class="animated fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid. Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut. Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore modi architecto.</p>
                <div>
                  <a href="<%= restaurants_menus_path(@restaurant.id) %>" class="btn-menu animated fadeIn scrollto">Nos menus</a>
                  <a href="<%= reservation_path(@restaurant.id) %>" class="btn-book animated fadeIn scrollto">Réserver</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</section>
<!-- End Hero -->

  <div class="container mt-5">

        <div class="info-wrap">
          <div class="row">
            <div class="col-lg-3 col-md-6 info">
              <i class="icofont-google-map"></i>
              <h4>Location:</h4>
              <p>A108 Adam Street<br>New York, NY 535022</p>
            </div>

            <div class="col-lg-3 col-md-6 info mt-4 mt-lg-0">
              <i class="icofont-clock-time icofont-rotate-90"></i>
              <h4>Open Hours:</h4>
              <p>Monday-Saturday:<br>11:00 AM - 2300 PM</p>
            </div>

            <div class="col-lg-3 col-md-6 info mt-4 mt-lg-0">
              <i class="icofont-envelope"></i>
              <h4>Email:</h4>
              <p>info@example.com<br>contact@example.com</p>
            </div>

            <div class="col-lg-3 col-md-6 info mt-4 mt-lg-0">
              <i class="icofont-phone"></i>
              <h4>Call:</h4>
              <p>+1 5589 55488 51<br>+1 5589 22475 14</p>
            </div>
          </div>
        </div>
      </div>

app/views/restos/update.html.erb
<h1>Restos#update</h1>
<p>Find me in app/views/restos/update.html.erb</p>